reddit_api:
  client_id: <>
  client_secret: <>
  user_agent: gabrissk
kafka:
  server: localhost:9092
  comments_topic: reddit-comments
  posts_topic: reddit-posts
s3:
  access_key: <>
  secret_key: <>
  output_path: reddit-data-viz-comments/reddit-api-data/
